spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/plm
    username: plm
    password: plm
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8081
